### ISSUE TITLE
Missed slash in remove_duplicate_slashes method

### ISSUE THREAD

**Issue by plenart** [toreau/URL-Normalize#2]
If "/" is just after "http://" method remove_duplicate_slashes  won't remove him. 

Example:
Before normalize:
http://///www......example.com/././.../////display?lang=en&article=fred
After normalize:
http:///www......example.com/display?lang=en&article=fred

**Comment by toreau** [comment]
`remove_duplicate_slashes` is intended to remove duplicate slashes from the URL's path. `http://///www......` isn't really a valid URL to begin with, so URL::Normalize should probably croak if given an invalid URL.
