### ISSUE TITLE
remove_dot_segments removes ending slash if we have anchor after it

### ISSUE THREAD

**Issue by cyga** [toreau/URL-Normalize#3]
$ perl -Ilib -MURL::Normalize -E'$n=URL::Normalize->new("https://hostname.tld/path/page/#anchor");say $n->url;$n->remove_dot_segments;say $n->url'
https://hostname.tld/path/page/#anchor
https://hostname.tld/path/page#anchor

Latest version atm:
$ perl -Ilib -MURL::Normalize -E'say $URL::Normalize::VERSION'
0.35

**Comment by toreau** [comment]
I'm sorry it's taken me so long to fix this, but version 0.37 is on its way out where this should be fixed. Please create a new issue if you still have problems.
